// qotd.js - Factorial's "Question of the Day" library, used for the daily recommendation widget.
// Each entry has loose topic tags pulled from the video's own YouTube tags - used to match
// against whatever chapter a student is currently working through.

export const QOTD = [
  {
    "title": "Factorial Question of the Day | A Beautiful Paragraph on Area Under Curves | Homework Included",
    "url": "https://www.youtube.com/watch?v=OWshDADosX0",
    "duration": "16:13",
    "tags": [
      "factorial academy",
      "question of the day",
      "area under curves",
      "definite integration",
      "calculus",
      "jee advanced",
      "jee advanced maths",
      "jee mains maths",
      "implicit functions",
      "implicit differentiation",
      "advanced calculus",
      "jee mathematics",
      "mathematical thinking",
      "challenging maths problems",
      "homework for jee",
      "area under curve questions",
      "jee 2026",
      "jee 2027",
      "jee 2028"
    ]
  },
  {
    "title": "Most Students Make This Mistake! | JEE Advanced 2010 Series Problem | Factorial Question of the Day",
    "url": "https://www.youtube.com/watch?v=uCSuE3dpwpQ",
    "duration": "9:08",
    "tags": [
      "jee advanced 2010",
      "jee advanced maths",
      "sequence and series",
      "infinite geometric progression",
      "gp series",
      "factorial problems",
      "modulus function",
      "jee advanced pyq",
      "factorial academy",
      "factorial question of the day",
      "jee advanced question",
      "series tricks",
      "mathematical observation",
      "advanced algebra",
      "jee 2026",
      "jee 2027",
      "jee 2028",
      "jee mathematics",
      "olympiad style problems",
      "hidden trap question"
    ]
  },
  {
    "title": "Definite Integration Meets Cauchy-Schwarz | A Hidden Gem for JEE Advanced | Factorial Q of the Day",
    "url": "https://www.youtube.com/watch?v=IyZikRgFsiQ",
    "duration": "7:54",
    "tags": [
      "jee advanced",
      "definite integration",
      "cauchy schwarz inequality",
      "cauchy inequality",
      "integral inequalities",
      "definite integration jee advanced",
      "jee advanced mathematics",
      "factorial academy",
      "question of the day",
      "factorial qotd",
      "advanced calculus",
      "integral form of cauchy schwarz",
      "inequality problems",
      "jee maths",
      "jee advanced preparation",
      "mathematical inequalities",
      "calculus tricks",
      "jee 2027",
      "jee 2028",
      "jee 2026",
      "integration techniques",
      "olympiad mathematics",
      "elegant proofs"
    ]
  },
  {
    "title": "Vector + Trigonometry + Differentiation = Magic | Factorial Question of the Day",
    "url": "https://www.youtube.com/watch?v=TU6l7YGq9Sk",
    "duration": "8:31",
    "tags": [
      "jee mains 2026",
      "jee mains 2026 maths",
      "jee main 4 april morning shift",
      "jee mains 4 april 2026",
      "jee mains maths questions",
      "jee mains memory based questions",
      "jee maths",
      "jee advanced maths",
      "factorial academy",
      "factorial question of the day",
      "qotd",
      "vectors jee mains",
      "trigonometry jee mains",
      "differentiation jee mains",
      "vector algebra",
      "trigonometric identities",
      "mathematics for jee",
      "jee mains pyq",
      "jee mains 2026 pyq",
      "beautiful maths problem",
      "jee aspirants",
      "jee 2027",
      "jee 2028"
    ]
  },
  {
    "title": "A Sequence That Hides a Beautiful Infinite Sum | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=cPQL5LRWJ70",
    "duration": "5:56",
    "tags": [
      "factorial academy",
      "factorial question of the day",
      "qotd",
      "jee advanced maths",
      "jee advanced question",
      "infinite series",
      "sequence and series",
      "recursive sequence",
      "telescoping series",
      "iit jee maths",
      "jee mathematics",
      "mathematics olympiad",
      "jee 2026",
      "jee 2027",
      "jee 2028",
      "advanced mathematics",
      "infinite sum",
      "maths shorts",
      "maths problem",
      "problem solving",
      "iit jee preparation"
    ]
  },
  {
    "title": "The Return of The Factorial Question of the Day 🚀 | JEE Advanced Algebra Problem | FQOTD #1",
    "url": "https://www.youtube.com/watch?v=EPDYbs1ZpIM",
    "duration": "8:51",
    "tags": [
      "jee advanced",
      "jee advanced maths",
      "question of the day",
      "factorial academy",
      "algebra",
      "maximum minimum",
      "real numbers",
      "jee mathematics",
      "iit jee",
      "jee 2026",
      "jee 2027",
      "jee 2028",
      "mathematical olympiad",
      "algebraic identities",
      "advanced algebra",
      "iit preparation",
      "jee problem solving",
      "maths challenge",
      "maximum value problem",
      "competitive mathematics"
    ]
  },
  {
    "title": "A Beautiful Logic Puzzle for JEE Aspirants | After a Long Break ❤️ | Factorial Question of the Day",
    "url": "https://www.youtube.com/watch?v=2PiQgnx3tdU",
    "duration": "8:00",
    "tags": [
      "jee maths",
      "jee 2027",
      "jee 2028",
      "set theory questions",
      "venn diagram problems",
      "jee advanced maths",
      "maths puzzle",
      "logical reasoning maths",
      "iit jee questions",
      "factorial academy",
      "counting problems",
      "jee aspirants",
      "mathematical logic",
      "jee pyq style questions",
      "smart maths tricks"
    ]
  },
  {
    "title": "Did You Make The Same Mistake? 😳 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=L0aZtE58WKI",
    "duration": "7:19",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "jee mains pyq",
      "jee previous yearsquestions",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee algebra",
      "jee trignometry",
      "jee vectors",
      "jee probability",
      "jee maths coaching",
      "online coaching"
    ]
  },
  {
    "title": "A Calculus Puzzle for JEE Advanced",
    "url": "https://www.youtube.com/watch?v=DVF6sKVUdqk",
    "duration": "13:48",
    "tags": [
      "jee advanced maths",
      "cauchy mean value theorem",
      "cmvt problem",
      "mean value theorem trick",
      "jee advanced inequality",
      "jee advanced calculus",
      "jee advanced maths question",
      "mean value theorem application",
      "calculus jee advanced",
      "iit jee maths",
      "factorial academy",
      "jee advanced preparation",
      "cmvt inequality problem"
    ]
  },
  {
    "title": "The Probability Question Everyone Solves Wrong | JEE Advanced Level",
    "url": "https://www.youtube.com/watch?v=NDVOMhAQxS8",
    "duration": "11:52",
    "tags": [
      "jee",
      "jee probability",
      "probability jee advanced",
      "jee advanced maths probability",
      "jee mains probability",
      "probability trap jee",
      "jee advanced tricky question",
      "factorial academy probability",
      "probability without replacement jee",
      "conditional probability jee advanced",
      "probability concept jee",
      "jee maths tough question",
      "jee advanced maths problem",
      "factorial question of the day",
      "jee advanced probability problem",
      "probability reasoning jee"
    ]
  },
  {
    "title": "A Classic Waiting Time Problem | JEE Advanced Probability | Factorial Question of the Day",
    "url": "https://www.youtube.com/watch?v=0w5T7xQOppo",
    "duration": "10:00",
    "tags": [
      "jee advanced probability",
      "probability jee advanced question",
      "jee advanced probability problems",
      "geometric probability jee",
      "waiting time probability problem",
      "random arrival probability",
      "jee advanced maths probability",
      "jee advanced maths problem",
      "jee advanced maths question",
      "factorial question of the day",
      "probability geometry trick",
      "coordinate geometry probability",
      "jee maths probability concept",
      "jee advanced 2026 maths",
      "difficult probability jee advanced"
    ]
  },
  {
    "title": "Only 1% Students See This Substitution | JEE Advanced 2026 | Definite Integration",
    "url": "https://www.youtube.com/watch?v=8PoeVW-_Eqc",
    "duration": "7:10",
    "tags": [
      "jee advanced definite integration",
      "improper integrals jee",
      "factorial question of the day",
      "jee advanced 2026 maths",
      "definite integration tricks",
      "gaussian integral jee",
      "advanced calculus jee",
      "substitution tricks integration",
      "jee maths high level problem",
      "factorial academy",
      "integration symmetry trick",
      "jee advanced level integral",
      "challenging integral problem"
    ]
  },
  {
    "title": "Most JEE Aspirants Got This WRONG | Inverse Function Trap",
    "url": "https://www.youtube.com/watch?v=1GWFbc48s_4",
    "duration": "28:20",
    "tags": [
      "jee",
      "jee advanced",
      "jee advanced maths",
      "inverse function jee",
      "function composition jee",
      "f inverse question",
      "monotonic function jee",
      "root counting techniques",
      "factorials question of the day",
      "jee 2026",
      "jee advanced 2026",
      "jee maths 2026"
    ]
  },
  {
    "title": "The Smallest Difference That Changes Everything | Built-In Limits | JEE Advanced 2026",
    "url": "https://www.youtube.com/watch?v=LWxUxVdwUo8",
    "duration": "12:42",
    "tags": [
      "factorial question of the day",
      "jee advanced maths",
      "limits jee advanced",
      "limit involving e",
      "n factorial limit problem",
      "advanced limit problems",
      "sine limit trick",
      "expansion of e problem",
      "jee 2026 maths preparation",
      "jee advanced 2026 maths",
      "challenging limits jee",
      "factorial academy maths",
      "jee maths conceptual problems",
      "high level limit problem"
    ]
  },
  {
    "title": "A Beautiful Trick Hidden Inside This Definite Integral",
    "url": "https://www.youtube.com/watch?v=XV4Ew6mFAhI",
    "duration": "8:07",
    "tags": [
      "jee advanced maths",
      "definite integration jee advanced",
      "tough definite integration",
      "logarithmic integral problem",
      "jee advanced 2026",
      "factorial academy",
      "calculus advanced problems",
      "integration tricks jee",
      "brilliant maths question",
      "i plus j integration problem",
      "jee maths 2026",
      "jee2026",
      "jeeadvanced2026",
      "jeemaths2026"
    ]
  },
  {
    "title": "Looks Impossible... But Collapses Beautifully! | JEE Advanced Maths",
    "url": "https://www.youtube.com/watch?v=3P1riyVHCqY",
    "duration": "11:45",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee advanced maths",
      "definite integration jee advanced",
      "functional integrals",
      "jee advanced 2026",
      "factorial academy",
      "hidden derivative integral",
      "advanced calculus jee",
      "jee maths daily problem",
      "factorial question of the day",
      "integration tricks jee",
      "conceptual calculus",
      "iit jee maths preparation",
      "jee advanced pyq style",
      "jee maths strategy",
      "integration structure problems",
      "challenging integrals jee"
    ]
  },
  {
    "title": "The Most Beautiful Telescoping Series You'll See Today | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=F7AB6ugwzMI",
    "duration": "11:06",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "jee mains pyq",
      "jee previous yearsquestions",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee algebra",
      "jee trignometry",
      "jee vectors",
      "jee probability",
      "jee maths coaching",
      "online coaching"
    ]
  },
  {
    "title": "Two Approaches to Solve This PNC Question | The Second Will Amaze You! | JEE 2025 | JEE 2026",
    "url": "https://www.youtube.com/watch?v=2BSIyTNGkGM",
    "duration": "9:57",
    "tags": [
      "jee advanced pnc",
      "jee mains pnc",
      "beggar's method",
      "pnc tricks for jee",
      "jee pnc shortcuts",
      "jee advanced 2025",
      "jee 2025 preparation",
      "factorial academy",
      "permutation and combination jee",
      "jee maths tricks",
      "jee problem-solving techniques",
      "pnc questions jee advanced",
      "innovative pnc solutions",
      "jee advanced pyqs",
      "competitive exam preparation"
    ]
  },
  {
    "title": "Students Miss This Detail - But It Changes Everything! | JEE Advanced 2023 | Circles",
    "url": "https://www.youtube.com/watch?v=KF5LCQoAUTs",
    "duration": "8:35",
    "tags": [
      "jee",
      "jee advanced",
      "jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "jee previous yearsquestions",
      "factorial academy",
      "jee advanced circles",
      "radical axis jee",
      "common tangents problem",
      "midpoint locus jee",
      "coordinate geometry jee",
      "jee 2023 question discussion",
      "factorials question of the day",
      "jee advanced 2026",
      "advanced geometry tricks",
      "hidden clue jee",
      "read the question carefully",
      "elegant circles problem",
      "tangent geometry jee",
      "ranker concept geometry"
    ]
  },
  {
    "title": "Two Brilliant P&C Methods for This JEE Advanced Problem!",
    "url": "https://www.youtube.com/watch?v=f5biCl3sQzo",
    "duration": "14:19",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "factorial academy",
      "jee probability",
      "pnc jee advanced",
      "inclusion exclusion jee",
      "student distribution problem jee",
      "no two together problem",
      "counting techniques jee",
      "factorials question of the day",
      "jee 2026 maths",
      "grouping pnc problems",
      "room distribution pnc",
      "restriction problems jee",
      "elegant pnc solution",
      "two methods pnc",
      "case method jee",
      "jee advanced combinatorics"
    ]
  },
  {
    "title": "Serious JEE advanced Aspirants MUST Learn This Idea! | Permutation & Combination | Regular Polygon",
    "url": "https://www.youtube.com/watch?v=-9bNgKtQD5I",
    "duration": "16:51",
    "tags": [
      "jee",
      "jee advanced",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee advanced pyqs",
      "jee previous yearsquestions",
      "factorial academy",
      "obtuse triangle in polygon",
      "regular polygon counting",
      "n-gon triangle problem",
      "jee advanced geometry",
      "pnc geometry mix",
      "factorials question of the day",
      "jee 2026 maths",
      "jee advanced 2026",
      "permutation and combination jee",
      "geometry combinatorics jee",
      "circle polygon problem",
      "serious jee aspirants",
      "ranker concept",
      "elegant geometry jee"
    ]
  },
  {
    "title": "Requested Problem:Hard to Read, Easy to Solve | Quadratic Equation",
    "url": "https://www.youtube.com/watch?v=XpqygyXtgeY",
    "duration": "6:23",
    "tags": [
      "jee",
      "jee advanced maths",
      "jee mains maths",
      "jee previous yearsquestions",
      "factorial academy",
      "jee algebra",
      "jee advanced algebra",
      "quadratic roots jee",
      "vieta formula jee",
      "symmetric expressions jee",
      "polynomial roots problem",
      "factorials question of the day",
      "jee advanced 2026",
      "jee maths trick",
      "elegant algebra method",
      "student requested problem",
      "algebra identity jee",
      "quadratic equation trick",
      "simplification tricks jee",
      "root symmetry",
      "jee mains and advanced maths",
      "ranker concept algebra"
    ]
  },
  {
    "title": "JEE Advanced: Nested Sum Collapses With One Elegant Idea!",
    "url": "https://www.youtube.com/watch?v=4zpTYYbPSKg",
    "duration": "10:05",
    "tags": [
      "jee advanced",
      "jee advanced maths",
      "jee pyq",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee algebra",
      "binomial theorem jee",
      "alternating sum jee",
      "integral trick jee",
      "convert sum to integral",
      "factorials question of the day",
      "nested sum jee",
      "elegant solution jee",
      "jee integral method",
      "binomial coefficient problem",
      "jee 2026 maths",
      "jee mains 2026",
      "ranker concept",
      "beautiful integral trick",
      "combinatorics meets calculus",
      "jee mathematics tricks",
      "advanced sum simplification"
    ]
  },
  {
    "title": "You'll Love How Smooth This Solution Is! | Permutations & Combinations",
    "url": "https://www.youtube.com/watch?v=i6fqPIwKnIM",
    "duration": "6:57",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "jee advanced maths",
      "jee previous yearsquestions",
      "factorial academy",
      "jee probability",
      "pnc jee advanced",
      "counting problems jee",
      "staircase problem jee",
      "fibonacci pnc logic",
      "factorials question of the day",
      "jee advanced 2026",
      "jee mains 2026",
      "elegant pnc problem",
      "smart counting trick",
      "step climbing problem",
      "forbidden step problem",
      "beautiful solution pnc",
      "ranker concept",
      "combinatorics jee",
      "1 or 2 steps counting"
    ]
  },
  {
    "title": "One of the Smartest Sitting Arrangement Questions Ever!| Permutations & Combinations | Probability",
    "url": "https://www.youtube.com/watch?v=Swn3f6aM474",
    "duration": "8:48",
    "tags": [
      "jee advanced maths",
      "jee previous yearsquestions",
      "factorial academy",
      "jee algebra",
      "jee probability",
      "jee advanced probability",
      "factorials question of the day",
      "jee 2026 maths",
      "jee advanced 2026",
      "jee mains 2026",
      "permutation and combination",
      "seating arrangement probability",
      "parity in probability",
      "elegant math problem",
      "jee advanced seating arrangement",
      "jee maths logic",
      "probability tricky question",
      "ranker level jee question",
      "elegant probability reasoning",
      "parity trick jee"
    ]
  },
  {
    "title": "You'll Love Both These Solutions! | Permutation & Combination",
    "url": "https://www.youtube.com/watch?v=hm0veGUCuXo",
    "duration": "9:34",
    "tags": [
      "jee advanced",
      "jee mains",
      "jee maths",
      "jee advanced maths",
      "jee pyq",
      "jee advanced pyqs",
      "factorial academy",
      "jee advanced pnc",
      "permutation and combination",
      "consecutive tickets problem",
      "factorials question of the day",
      "jee 2026 maths",
      "elegant counting",
      "pnc logic",
      "combinatorics jee",
      "gap method pnc",
      "distribution problem",
      "two methods same result",
      "jee advanced 2026",
      "jee mains 2026",
      "factorial academy jee",
      "pnc for jee",
      "ranker level question",
      "double approach jee",
      "counting problem jee"
    ]
  },
  {
    "title": "The \"Impossible\" JEE Advanced Probability Question (Explained!) | JEE Advanced 2021 - The Nightmare",
    "url": "https://www.youtube.com/watch?v=ACW1kE3t6mA",
    "duration": "19:42",
    "tags": [
      "jee advanced pyqs",
      "factorial academy",
      "jee probability",
      "jee advanced 2021 probability",
      "factorials question of the day",
      "jee advanced probability",
      "conditional probability",
      "hard jee advanced question",
      "jee 2026 maths",
      "jee advanced 2026",
      "jee mains 2026",
      "jee advanced sets problem",
      "probability chain logic",
      "advanced maths problem",
      "ranker level jee",
      "tough probability jee",
      "iit jee 2021 paper discussion",
      "impossible jee question",
      "factorial academy jee",
      "advanced probability jee"
    ]
  },
  {
    "title": "Famous Stick–Triangle Problem | JEE Advanced 2026 | Probability",
    "url": "https://www.youtube.com/watch?v=Fg5yFczII4M",
    "duration": "10:04",
    "tags": [
      "jee",
      "jee advanced",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee advanced pyqs",
      "jee previous yearsquestions",
      "factorial academy",
      "jee probability",
      "probability",
      "geometric probability",
      "triangle formation probability",
      "break stick probability",
      "jee advanced probability",
      "jee mains probability",
      "jee 2026 maths",
      "jee advanced 2026",
      "triangle condition",
      "ranker trick probability",
      "classic probability problem",
      "conditional probability geometry",
      "qotd factorial"
    ]
  },
  {
    "title": "A Gem from Complex Numbers You MUST Know",
    "url": "https://www.youtube.com/watch?v=pCGSWNXYsa0",
    "duration": "6:36",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee pyq",
      "jee advanced pyqs",
      "factorial academy",
      "complex numbers",
      "modulus inequality",
      "jee advanced complex numbers",
      "conjugate trick",
      "complex plane geometry",
      "bound on modulus",
      "jee 2026 maths",
      "complex number transformation",
      "mobius transformation jee",
      "complex algebra jee",
      "conjugation tricks",
      "jee maths question of the day",
      "z1 z2 z3 z4 jee",
      "jee advanced 2026",
      "jee mains 2026",
      "smart complex idea"
    ]
  },
  {
    "title": "A Beautiful Remainder Trick | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=OCdd3vOfs_k",
    "duration": "5:34",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee advanced pyqs",
      "jee previous yearsquestions",
      "factorial academy"
    ]
  },
  {
    "title": "Serious JEE Advanced Stuff - Elegant Reduction Move | Definite Integration",
    "url": "https://www.youtube.com/watch?v=qWCNFF9HNlQ",
    "duration": "12:03",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee pyq",
      "jee advanced pyqs",
      "factorial academy",
      "jee calculus",
      "jee advanced 2025",
      "jee 2026",
      "factorial's question of the day",
      "definite integration",
      "reduction formula",
      "recurrence relation",
      "jee advanced calculus",
      "advanced integration tricks",
      "integration by parts",
      "symmetry in integrals",
      "series of integrals",
      "tough jee problems",
      "problem solving jee",
      "jee maths concepts",
      "jee advanced practice"
    ]
  },
  {
    "title": "Complex Numbers at Their Best | Factorial's Question of The Day | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=rIjTbbgHGFs",
    "duration": "10:37",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "factorial academy",
      "factorial maths",
      "ee advanced",
      "jee advanced 2025",
      "jee 2026",
      "complex numbers jee",
      "complex geometry",
      "modulus inequality",
      "triangle inequality jee",
      "vector approach complex",
      "advanced maths problem",
      "factorial question of the day",
      "jee problem solving",
      "jee maths concepts",
      "jee advanced practice",
      "geometry through complex numbers"
    ]
  },
  {
    "title": "When a Student Sent Me This JEE Advanced Limit Problem...",
    "url": "https://www.youtube.com/watch?v=Rzcjiv_9BZQ",
    "duration": "8:16",
    "tags": [
      "jee",
      "jee advanced",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "jee mains pyq",
      "jee previous yearsquestions",
      "factorial academy",
      "factorial's question of the day",
      "student requested question",
      "advanced maths problem",
      "limits and integration",
      "tricky jee question",
      "calculus jee advanced",
      "jee advanced previous year questions",
      "jee advanced important questions",
      "advanced calculus",
      "jee advanced motivation",
      "factorial question of the day"
    ]
  },
  {
    "title": "A Question That Defines 'Conceptual Mastery' in JEE",
    "url": "https://www.youtube.com/watch?v=qVX1pltOc_c",
    "duration": "9:34",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "jee mains pyq",
      "jee previous yearsquestions",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee algebra",
      "jee trignometry",
      "jee vectors",
      "jee probability",
      "jee maths coaching",
      "online coaching"
    ]
  },
  {
    "title": "Only a Few Could Think THIS Way | Genius",
    "url": "https://www.youtube.com/watch?v=ZzgZ19pkK3s",
    "duration": "7:46",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee advanced pyqs",
      "jee mains pyq",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee advanced",
      "jee maths",
      "factorial academy",
      "integration tricks",
      "limit questions",
      "jee definite integration",
      "jee series problems",
      "tricky jee problems",
      "factorials question of the day"
    ]
  },
  {
    "title": "Most Students Gave Up on This Series Problem - Can You Solve It?",
    "url": "https://www.youtube.com/watch?v=fG_BLGEHi8U",
    "duration": "8:18",
    "tags": [
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee sequence and series",
      "jee limit problem",
      "recursion and limit",
      "jee tricky question",
      "jee advanced 2025 preparation",
      "sequence formula derivation",
      "recursion in jee",
      "jee main advanced difference",
      "factorial academy maths"
    ]
  },
  {
    "title": "This JEE Integral Has More Depth Than You Think 😯",
    "url": "https://www.youtube.com/watch?v=uc-LvZv8NtI",
    "duration": "7:26",
    "tags": [
      "jee",
      "jee advanced",
      "iit jee",
      "jee mains",
      "jee maths",
      "iit jee maths",
      "jee advanced maths",
      "jee mains maths",
      "jee pyq",
      "jee advanced pyqs",
      "jee mains pyq",
      "jee previous yearsquestions",
      "factorial academy",
      "factorial maths",
      "jee calculus",
      "jee algebra",
      "jee trignometry",
      "jee vectors",
      "jee probability",
      "jee maths coaching",
      "online coaching"
    ]
  },
  {
    "title": "The Most Elegant Way to Solve This Polynomial Question 🔥",
    "url": "https://www.youtube.com/watch?v=zJrIFLmQ998",
    "duration": "7:39",
    "tags": [
      "jee advanced 2025",
      "jee mains",
      "polynomial maxima minima",
      "jee calculus tricks",
      "jee advanced polynomial questions",
      "jee problem solving",
      "factorial academy",
      "smart approach calculus",
      "polynomial concepts",
      "calculus symmetry",
      "jee topper strategy"
    ]
  },
  {
    "title": "You'll Love How Complex Numbers Solve This!",
    "url": "https://www.youtube.com/watch?v=ACM5jBJq6sc",
    "duration": "12:13",
    "tags": [
      "jee advanced 2025",
      "jee main 2025",
      "jee maths",
      "complex numbers jee",
      "geometry through complex numbers",
      "factorial academy",
      "jee advanced pyq",
      "jee main pyq",
      "jee concepts",
      "jee revision",
      "jee tips",
      "iit jee maths",
      "complex number geometry",
      "jee problem solving",
      "jee tricks",
      "jee strategy"
    ]
  },
  {
    "title": "💥 100 Problems. 100 Concepts | The Ultimate JEE Concept Fireworks - All 100 Questions in One Place!",
    "url": "https://www.youtube.com/watch?v=cyBssrEjpdE",
    "duration": "9:29",
    "tags": [
      "jee",
      "jee advanced",
      "jee mains",
      "factorial academy",
      "question of the day",
      "jee revision",
      "jee concepts",
      "jee 2025",
      "iit jee",
      "jee maths",
      "concept revision",
      "jee practice",
      "jee motivation",
      "jee short notes",
      "jee question bank",
      "conic sections",
      "calculus",
      "algebra",
      "coordinate geometry",
      "limits",
      "integration",
      "factorial question series",
      "jee problem solving",
      "diwali special",
      "maths for jee"
    ]
  },
  {
    "title": "Just One Observation Changes the Whole Question!",
    "url": "https://www.youtube.com/watch?v=cKIt9LatbGE",
    "duration": "8:29",
    "tags": [
      "jee",
      "jeemains",
      "jeeadvanced",
      "jeemaths",
      "conicsections",
      "parabola",
      "hyperbola",
      "ellipse",
      "jeequadratic",
      "jeepreparation",
      "jeeconcepts",
      "iitjee",
      "iitjeemaths",
      "jeerevision",
      "jeepractice",
      "factorialacademy",
      "facto",
      "mathsforjee",
      "jeetricks",
      "jee2025",
      "jee2026"
    ]
  },
  {
    "title": "One Powerful Question + 2 Game-Changing Parabola Properties (With Proofs!)",
    "url": "https://www.youtube.com/watch?v=NMbb98pEGpA",
    "duration": "18:00",
    "tags": [
      "jee parabola",
      "parabola properties",
      "focus directrix tangent",
      "jee conic section",
      "jee maths",
      "factorial academy",
      "jee mains previous year questions",
      "jee important concepts",
      "jee geometry",
      "jee tricks",
      "jee maths lecture",
      "jee parabola concepts",
      "jee advanced preparation",
      "jee revision",
      "jee2026"
    ]
  },
  {
    "title": "Don't Miss This Subtle JEE Limit Question!✅",
    "url": "https://www.youtube.com/watch?v=ihrXBKcoPrU",
    "duration": "7:26",
    "tags": [
      "jee mains 2025",
      "jee advanced 2025",
      "jee limits questions",
      "greatest integer function jee",
      "limit tricks jee",
      "jee mains important questions",
      "calculus jee problems",
      "jee advanced maths",
      "factorial academy",
      "factorial academy jee",
      "limit and continuity",
      "tricky jee limits",
      "jee 2025 preparation",
      "jee mains chapterwise practice",
      "jee limit questions with gif",
      "factorial question of the day",
      "jee maths problem solving"
    ]
  },
  {
    "title": "One of the Most Elegant Ellipse Questions for JEE Advanced",
    "url": "https://www.youtube.com/watch?v=bvm5-kmLIR4",
    "duration": "9:30",
    "tags": [
      "jee mains 2025",
      "jee advanced 2025",
      "conic sections",
      "ellipse questions jee",
      "circle and ellipse jee problem",
      "coordinate geometry jee",
      "jee previous year questions",
      "jee 2025 preparation",
      "jee mains important questions",
      "conic geometry tricks",
      "jee problem solving",
      "jee mains ellipse",
      "jee coordinate geometry",
      "ellipse tangent normal",
      "jee conic combo",
      "jee advanced geometry",
      "factorial academy"
    ]
  },
  {
    "title": "When Parabola & Circle Meet | This One Deserves a Spot in Your Notes",
    "url": "https://www.youtube.com/watch?v=6-fg2zfObpg",
    "duration": "7:58",
    "tags": [
      "jee maths",
      "jee advanced",
      "jee main",
      "parabola normal chord",
      "conic geometry",
      "coordinate geometry jee",
      "factorial academy",
      "jee advanced geometry",
      "parabola jee questions",
      "jee 2025 preparation",
      "jee advanced previous year",
      "jee conceptual maths"
    ]
  },
  {
    "title": "The 100th One! | Brilliant Geometry Problem from Circles | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=8_GqIsWNKvM",
    "duration": "8:14",
    "tags": [
      "jee maths",
      "jee advanced",
      "jee main",
      "jee coordinate geometry",
      "circles jee",
      "tangent and radical axis",
      "jee 2025 preparation",
      "factorial academy",
      "jee geometry",
      "jee advanced problem solving",
      "jee previous year questions",
      "jee tricky problems",
      "jee conceptual questions"
    ]
  },
  {
    "title": "This JEE Problem Looks Messy... Until You See It Clearly!  | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=JilBH9SFM_o",
    "duration": "8:00",
    "tags": [
      "jee maths",
      "jee advanced",
      "jee problem solving",
      "jee main",
      "factorial academy",
      "tricky jee question",
      "conceptual jee maths",
      "jee 2025 preparation",
      "problem solving mindset",
      "hidden pattern jee",
      "jee function minimization"
    ]
  },
  {
    "title": "A Very Different JEE Advanced Question | Geometry + 3D Visualisation | JEE PYQs",
    "url": "https://www.youtube.com/watch?v=CO2vC7ZGyEE",
    "duration": "13:08",
    "tags": [
      "jee advanced 2022",
      "jee 2022 pyq",
      "jee advanced 3d geometry",
      "jee advanced planes question",
      "jee tetrahedron problem",
      "jee 3d line plane intersection",
      "jee geometry concept",
      "factorial academy",
      "jee advanced analysis",
      "jee advanced previous year question",
      "jee advanced discussion",
      "jee problem solving"
    ]
  },
  {
    "title": "Good Problem, Better Method - ITF Summation Series | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=XS9vLPNhE7w",
    "duration": "5:50",
    "tags": [
      "jee advanced trigonometry",
      "jee summation problems",
      "inverse trigonometric functions jee",
      "telescoping series jee",
      "beautiful jee problems",
      "jee advanced maths",
      "factorial academy",
      "trigonometric series jee"
    ]
  },
  {
    "title": "JEE Advanced Problem on Regular Polygon & Complex Numbers",
    "url": "https://www.youtube.com/watch?v=cpe4iXXZZM0",
    "duration": "6:30",
    "tags": [
      "jee complex numbers",
      "complex geometry jee",
      "regular polygon complex plane",
      "geometry using complex numbers",
      "jee advanced maths",
      "complex numbers jee tricks",
      "factorial academy",
      "jee maths concepts"
    ]
  },
  {
    "title": "JEE Advanced 3-in-1 Concept Problem | Composite, Inverse & Derivative",
    "url": "https://www.youtube.com/watch?v=l8oR4Z94tSc",
    "duration": "11:21",
    "tags": [
      "jee advanced functions",
      "inverse function jee",
      "differentiation problems jee",
      "composition of functions",
      "functional equations jee advanced",
      "jee main maths tricks",
      "factorial academy",
      "tough jee maths problems",
      "advanced function questions"
    ]
  },
  {
    "title": "Ultimate Limit Problem That Tests it All! | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=IVAHOGfDEPc",
    "duration": "14:29",
    "tags": [
      "jee advanced limits",
      "definite integration jee",
      "built-in limit",
      "jee main maths",
      "iit jee calculus",
      "jee maths tricks",
      "advanced maths problems",
      "factorial academy",
      "jee conceptual maths",
      "factorial academy"
    ]
  },
  {
    "title": "From Monster Expression to Answer in Seconds! | Sophie Germain Factorisation",
    "url": "https://www.youtube.com/watch?v=uH0_T7tc9lc",
    "duration": "5:51",
    "tags": [
      "factorial academy",
      "jee",
      "jee advanced",
      "jee mains",
      "iit jee",
      "algebra",
      "factorisation",
      "sophie germain identity",
      "sophie germain factorisation",
      "telescoping products",
      "algebra tricks",
      "algebra shortcuts",
      "math tricks",
      "math olympiad",
      "amti",
      "olympiad algebra",
      "beautiful algebra",
      "complex numbers",
      "polynomial factorisation",
      "jee algebra",
      "advanced algebra problems",
      "jee advanced algebra",
      "algebra patterns",
      "algebra simplification",
      "problem solving",
      "competitive math",
      "mathematical beauty"
    ]
  },
  {
    "title": "Beautiful JEE Advanced Problem | Roots of Cubic Equation",
    "url": "https://www.youtube.com/watch?v=WG5t8CdPD1U",
    "duration": "11:55",
    "tags": [
      "jee advanced 2025 maths",
      "cubic equations jee",
      "nature of roots jee",
      "jee match the column",
      "advanced maths tricks",
      "roots of cubic equation",
      "iit jee problem solving",
      "jee advanced previous year questions",
      "factorial academy"
    ]
  },
  {
    "title": "Most Ignored JEE Limit Concept | Built-in Limit Explained | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=QaZ_sSCIK3U",
    "duration": "5:59",
    "tags": [
      "jee limits",
      "built in limit jee",
      "jee advanced limits",
      "limit jee mains",
      "iit jee maths",
      "jee maths tricks",
      "advanced maths jee",
      "factorial academy"
    ]
  },
  {
    "title": "Beautiful Maths: Recurrence to Limit | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=tmi3ptnugNU",
    "duration": "7:36",
    "tags": [
      "jee advanced limits problem",
      "jee advanced recurrence relation",
      "limit problems for iit jee",
      "jee advanced maths questions",
      "iit jee 2026 preparation",
      "factorial academy maths",
      "sequence and series jee",
      "limits jee mains advanced",
      "recurrence relation jee advanced",
      "iit jee tricks maths"
    ]
  },
  {
    "title": "Elegant Integration Problem Solved 🔥 | Definite Integration | JEE 2026",
    "url": "https://www.youtube.com/watch?v=ErHODsgARGU",
    "duration": "5:46",
    "tags": [
      "definite integration jee",
      "jee advanced integration",
      "absolute value definite integration",
      "integration tricks jee",
      "factorial academy",
      "beautiful definite integration",
      "maths jee advanced 2025",
      "definite integration problem solving",
      "jee mains and advanced maths",
      "iit jee definite integration"
    ]
  },
  {
    "title": "Beautiful JEE Advanced 2025 Vectors Question Solved | JEE Advanced PYQs",
    "url": "https://www.youtube.com/watch?v=3VPGxjQsPow",
    "duration": "9:01",
    "tags": [
      "jee advanced 2025",
      "jee advanced 2025 paper 1",
      "jee advanced vectors",
      "vectors jee advanced",
      "vectors iit jee",
      "factorial academy",
      "jee advanced maths 2025",
      "vectors problem solving",
      "challenging vectors question",
      "iit jee advanced solutions"
    ]
  },
  {
    "title": "Don't Skip This Question | Straight Line | JEE 2026",
    "url": "https://www.youtube.com/watch?v=fR_vEPaQ7vs",
    "duration": "4:40",
    "tags": [
      "jee straight line quadratic equation",
      "jee straight line problem",
      "quadratic equation jee",
      "straight line jee advanced",
      "straight line jee main",
      "quadratic equation trick jee",
      "intersection straight line quadratic",
      "jee maths problem solving",
      "jee algebra and coordinate geometry",
      "factorial academy"
    ]
  },
  {
    "title": "Smart Approach to Minimize Sum of Squares | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=gYb_iVUDN28",
    "duration": "7:40",
    "tags": [
      "jee quadratic inequality",
      "jee system of equations",
      "jee optimization problem",
      "jee maths trick",
      "minimize sum of squares",
      "jee main algebra problem",
      "jee advanced algebra",
      "jee vector method",
      "factorial academy",
      "3d",
      "vector",
      "plane",
      "3d geometry"
    ]
  },
  {
    "title": "A Definite Integration Problem with Infinite Series Twist | JEE ADVANCED 2026",
    "url": "https://www.youtube.com/watch?v=DEbSKAd60jY",
    "duration": "8:41",
    "tags": [
      "definite integration jee",
      "infinite series jee",
      "integration with series",
      "challenging jee problems",
      "mathematics iit jee",
      "factorial academy",
      "advanced calculus jee",
      "integration tricks",
      "series problems jee advanced",
      "definite integration with series"
    ]
  },
  {
    "title": "Mix of Implicit + Inverse Function in ONE Question | JEE ADVANCED 2026",
    "url": "https://www.youtube.com/watch?v=JjJhRRO6r9o",
    "duration": "7:33",
    "tags": [
      "jee advanced maths",
      "inverse function problem",
      "implicit differentiation jee",
      "advanced derivative problem",
      "challenging jee question",
      "factorial academy",
      "iit jee maths",
      "tough derivatives",
      "functions and inverse",
      "calculus problem solving"
    ]
  },
  {
    "title": "Cycle Decomposition in JEE | Functions + PnC Problem | JEE Advanced 2026",
    "url": "https://www.youtube.com/watch?v=ZIO2B4JoUIQ",
    "duration": "10:02",
    "tags": [
      "jee advanced functions pnc",
      "functions and permutations jee",
      "jeemain functions problems",
      "jee advanced functions problems",
      "permutation and combination jee advanced",
      "functions f(f(f(x))) problem",
      "jee tricky problems",
      "jee killer problems"
    ]
  },
  {
    "title": "This single problem filters out the best problem solvers | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=dl8iePgE8JQ",
    "duration": "5:01",
    "tags": [
      "jee",
      "algebra",
      "vectors",
      "math challenge",
      "iitjee",
      "contest math",
      "factorial academy",
      "problem solving",
      "max min problems"
    ]
  },
  {
    "title": "Two elegant methods to crack this power sum puzzle | JEE Advanced | 2026 | 2027",
    "url": "https://www.youtube.com/watch?v=hC2I8gmkg3A",
    "duration": "9:41",
    "tags": [
      "algebra",
      "symmetric sums",
      "power sums",
      "newton identities",
      "jee",
      "iitjee",
      "math puzzle",
      "factorial academy",
      "polynomial roots",
      "problem solving",
      "contest math"
    ]
  },
  {
    "title": "This integral equation stumps most students! | Definite Integration",
    "url": "https://www.youtube.com/watch?v=gxucfn5v8eU",
    "duration": "7:23",
    "tags": [
      "calculus",
      "integral",
      "jee",
      "am gm",
      "inequalities",
      "functional equations",
      "continuous functions",
      "analysis",
      "factorial academy",
      "math problem",
      "solution"
    ]
  },
  {
    "title": "From Complicated to Simple: Recurrence Relation Solved Conceptually | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=xGHkGRGHwsw",
    "duration": "6:07",
    "tags": [
      "jee advanced recurrence problems",
      "recurrence relation jee",
      "periodic recurrence jee",
      "sequences and series jee",
      "recurrence relation iit jee",
      "limit of recurrence sequence",
      "jee math sequence problems",
      "hidden periodicity in sequences",
      "recurrence invariant method",
      "factorial academy math",
      "iit jee advanced 2025 math",
      "jee mains 2025 sequences",
      "recurrence relation periodicity",
      "period 5 sequence jee",
      "jee advanced limits questions",
      "olympiad recurrence problems",
      "beautiful math problems jee"
    ]
  },
  {
    "title": "Beautiful Recursion + Limit Problem | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=qTY-Q9e5Xk8",
    "duration": "8:00",
    "tags": [
      "jee advanced",
      "jee advanced 2026",
      "jee advanced maths",
      "iit jee",
      "iit jee maths",
      "recursion problems",
      "limit problems",
      "beautiful math problems",
      "jee limits",
      "recursive limits",
      "math telescoping trick",
      "euler's number e",
      "calculus problems jee",
      "important jee problems",
      "factorial academy"
    ]
  },
  {
    "title": "Conceptual Matrices Problem | Commutativity & Invertibility | JEE Advanced",
    "url": "https://www.youtube.com/watch?v=XmnhKXF9qxk",
    "duration": "7:19",
    "tags": [
      "jee mains",
      "jee advanced",
      "jee 2025",
      "jee maths",
      "matrix problem jee",
      "commutative matrices",
      "invertibility jee",
      "algebra jee",
      "factorial academy",
      "jee advanced maths important",
      "matrices",
      "jee2026"
    ]
  },
  {
    "title": "This Matrix Question LOOKS TOUGH but is Actually Easy!",
    "url": "https://www.youtube.com/watch?v=ah5ZQUz84jI",
    "duration": "5:38",
    "tags": [
      "jee mains",
      "jee advanced",
      "jee maths",
      "matrix inequality problem",
      "determinant jee",
      "application of matrices jee",
      "jee 2025 maths",
      "factorial academy"
    ]
  },
  {
    "title": "Can You Solve this Tricky Differential Equation? | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=ZEKrZwKmX8Y",
    "duration": "6:07",
    "tags": [
      "differential equation",
      "exact differential equation",
      "integrating factor",
      "calculus tricks",
      "jee advanced math",
      "iit jee preparation",
      "ode solution",
      "factorial academy",
      "math problem solving",
      "jee mains"
    ]
  },
  {
    "title": "Can You Solve This Area Puzzle in 2 Minutes?",
    "url": "https://www.youtube.com/watch?v=AsOy5jB6tMI",
    "duration": "6:17",
    "tags": [
      "jee advanced maths",
      "jee mains maths",
      "greatest integer function jee",
      "area under curve jee",
      "jee advanced area problem",
      "factorial academy",
      "jee maths challenge"
    ]
  },
  {
    "title": "This Area Question Blew My Mind! | Factorial's Question of the Day | JEE",
    "url": "https://www.youtube.com/watch?v=DqqcdY0B8j8",
    "duration": "13:05",
    "tags": [
      "jee advanced",
      "jee mains",
      "geometry problem",
      "area by rotation",
      "coordinate geometry",
      "rotation of points",
      "iit jee previous year question",
      "factorial academy",
      "math tricks",
      "jee problem solving",
      "beautiful math problems",
      "advanced geometry"
    ]
  },
  {
    "title": "A Genius Integral That Looks Tough but Cracks Easily!",
    "url": "https://www.youtube.com/watch?v=be5Gm6S9NGU",
    "duration": "8:30",
    "tags": [
      "jee advanced maths",
      "jee advanced integration",
      "greatest integer function integral",
      "arctan integral jee",
      "jee advanced 2025",
      "iit jee maths tricks",
      "brilliant jee maths",
      "beautiful integral problem",
      "integration tricks for jee",
      "jee mains and advanced calculus",
      "challenging integral problem",
      "2 minute integral challenge",
      "jee maths shortcuts",
      "advanced calculus jee",
      "maths problem solving tricks",
      "brilliant integration question",
      "best maths tricks for iit jee"
    ]
  },
  {
    "title": "Least Area Problem | Applications of Integrals | JEE Concept Booster",
    "url": "https://www.youtube.com/watch?v=o1itulHbNGU",
    "duration": "8:34",
    "tags": [
      "jee mains",
      "jee advanced",
      "parabola line area",
      "applications of integrals jee",
      "area bounded by parabola and line",
      "definite integration jee",
      "factorial academy",
      "least area problems jee"
    ]
  },
  {
    "title": "A Beautiful Fusion: Algebra + Graphs in Action | Cubic Equation",
    "url": "https://www.youtube.com/watch?v=T9BIGD8NmCg",
    "duration": "9:16",
    "tags": [
      "algebraic symmetry",
      "real roots",
      "graph approach",
      "cubic equation tricks",
      "iit jee algebra problems",
      "jee advanced 2025",
      "iit jee preparation",
      "factorial academy",
      "symmetry in mathematics",
      "jee maths tricks",
      "problem solving with graphs",
      "elegant maths problems"
    ]
  },
  {
    "title": "Double Summation Demystified | Binomial Theorem",
    "url": "https://www.youtube.com/watch?v=2fHif0AD0VM",
    "duration": "12:47",
    "tags": [
      "binomial theorem",
      "double summation",
      "jee binomial theorem",
      "binomial problems",
      "iit jee math",
      "jee advanced binomial",
      "jee algebra",
      "tough binomial theorem problems",
      "factorial academy",
      "jee 2025 math",
      "jee advanced preparation"
    ]
  },
  {
    "title": "This Question Has Everything: Binomial + Differentiation + Integration",
    "url": "https://www.youtube.com/watch?v=iXFvZyAlrWA",
    "duration": "14:29",
    "tags": [
      "jee maths",
      "jee advanced maths",
      "jee binomial theorem",
      "jee differentiation",
      "jee definite integration",
      "algebra meets calculus",
      "brilliant jee problem",
      "jee problem solving",
      "factorial academy",
      "jee advanced previous year question",
      "jee algebra calculus mi"
    ]
  },
  {
    "title": "A Beautiful Crossover Problem from Integral Calculus",
    "url": "https://www.youtube.com/watch?v=x9Lpt4liXZ0",
    "duration": "12:17",
    "tags": [
      "definite integration",
      "differential equations",
      "integral calculus",
      "jee maths",
      "factorial academy",
      "jee mains 2025 maths",
      "jee advanced 2025 maths",
      "calculus crossover",
      "integration with de",
      "beautiful maths problem",
      "multi concept maths",
      "integration tricks",
      "jee integration"
    ]
  },
  {
    "title": "A Brilliant Binomial Theorem Problem | From Chaos to Peace",
    "url": "https://www.youtube.com/watch?v=cd67Bb4kbGI",
    "duration": "9:29",
    "tags": [
      "binomial theorem",
      "finite differences",
      "combinatorics trick",
      "jee maths",
      "factorial academy",
      "101^4",
      "jee advanced maths",
      "combinatorial identities",
      "math trick",
      "jee mains maths",
      "binomial sum trick",
      "beautiful maths problems",
      "discrete mathematics",
      "polynomial differences"
    ]
  },
  {
    "title": "A Small Clue That Changes Everything in This Integral",
    "url": "https://www.youtube.com/watch?v=THEGRbtGEno",
    "duration": "11:11",
    "tags": [
      "jee advanced maths",
      "definite integration",
      "iit jee preparation",
      "integration tricks",
      "jee main maths",
      "calculus jee",
      "advanced maths problems",
      "jee 2025",
      "limit of an integral",
      "factorial academy",
      "symmetry in integration",
      "integration shortcuts",
      "problem solving techniques",
      "jee advanced 2025 maths solutions"
    ]
  },
  {
    "title": "This Question Destroyed My First Impression... and I Loved It!",
    "url": "https://www.youtube.com/watch?v=rMViXIOzNEY",
    "duration": "10:13",
    "tags": [
      "jee advanced maths",
      "definite integration",
      "summation problems",
      "telescoping series",
      "maths tricks",
      "jee advanced 2025",
      "jee main 2025",
      "calculus jee",
      "iit jee preparation",
      "integration techniques",
      "infinite series",
      "advanced maths problems",
      "summation integration combined",
      "factorial academy",
      "iit jee maths tricks"
    ]
  },
  {
    "title": "Definite Integration Gem for JEE Advanced | Euler-Poisson | Feynman's Trick",
    "url": "https://www.youtube.com/watch?v=BItV6LnVAmw",
    "duration": "15:04",
    "tags": [
      "jee advanced maths",
      "jee mains maths",
      "jee advanced integration",
      "jee mains integration tricks",
      "euler poisson integral",
      "definite integration jee",
      "log integral trick",
      "symmetry in integration",
      "integration tricks",
      "jee maths short tricks",
      "calculus jee",
      "factorial academy",
      "integration by differentiation under the integral sign",
      "jee advanced past year question",
      "log trig integral"
    ]
  },
  {
    "title": "A Truly Challenging JEE Advanced Integration Problem | Definite Integration",
    "url": "https://www.youtube.com/watch?v=P-Fn5T6t1LE",
    "duration": "9:59",
    "tags": [
      "difficult definite integration",
      "jee advanced definite integration",
      "inverse function integration",
      "area under curve jee advanced",
      "jee advanced maths tricks",
      "definite integration iit jee",
      "jee maths problem solving",
      "factorial academy"
    ]
  },
  {
    "title": "This Double Summation Concept is GOLD for JEE Advanced | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=Ha0C4t_0AXg",
    "duration": "14:28",
    "tags": [
      "double summation to integration",
      "double sigma simplification",
      "jee advanced maths tricks",
      "definite integration jee advanced",
      "limits jee advanced",
      "summation to integration",
      "jee advanced series",
      "iit jee maths problem solving",
      "factorial academy"
    ]
  },
  {
    "title": "This One Integration Idea Simplifies So Many Problems | Definite Integration",
    "url": "https://www.youtube.com/watch?v=bm_qAvY8OZs",
    "duration": "5:01",
    "tags": [
      "definite integration",
      "integration tricks",
      "area under curve",
      "area and integration",
      "jee mains maths",
      "jee advanced calculus",
      "symmetry in integration",
      "beautiful calculus problems",
      "jee 2025 maths",
      "factorial academy",
      "integration concept jee",
      "integral with area interpretation",
      "definite integral trick",
      "math short trick",
      "jee mains 2025"
    ]
  },
  {
    "title": "A Student Sent Me This MIT Integral. It Looks Intense - But It's Easy!",
    "url": "https://www.youtube.com/watch?v=ZIZkjiziY6E",
    "duration": "4:54",
    "tags": [
      "mit integration problem",
      "jee advanced math",
      "definite integration",
      "integration tricks",
      "exponential function",
      "math olympiad",
      "mit entrance questions",
      "hard integrals solved",
      "iit jee maths",
      "factorial academy",
      "beautiful integration problems"
    ]
  },
  {
    "title": "Looks Complex? Solved in 10 Seconds! 🔥 | Definite Integration",
    "url": "https://www.youtube.com/watch?v=VKN4gmdQRMQ",
    "duration": "4:12",
    "tags": [
      "calculus",
      "integral trick",
      "nested radicals",
      "jee preparation",
      "math shortcut",
      "definite integral",
      "substitution",
      "square roots",
      "problem solving",
      "exam math",
      "competitive math",
      "high school math",
      "college math",
      "integration hack",
      "factorial questions",
      "factorial academy"
    ]
  },
  {
    "title": "Only 1 Function Maximizes This Integral | Can You Find It? | JEE 2026",
    "url": "https://www.youtube.com/watch?v=oSdHFtzmb6w",
    "duration": "6:35",
    "tags": [
      "iit jee advanced",
      "definite integration",
      "functional maximization",
      "calculus optimization",
      "jee calculus",
      "jee integration",
      "advanced calculus",
      "jee 2025",
      "jee mains advanced",
      "math tricks",
      "integration problems"
    ]
  },
  {
    "title": "A Conceptual Goldmine from Definite Integration 🔥| Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=PbLlqeokTM0",
    "duration": "11:32",
    "tags": [
      "jee advanced maths",
      "greatest integer function",
      "double integral jee advanced",
      "discontinuity of functions",
      "iit jee 2025 maths",
      "advanced integration problems",
      "f(x) discontinuity jee",
      "jee maths concept",
      "factorial academy maths",
      "continuity and differentiability jee"
    ]
  },
  {
    "title": "This \"Scary\" Limit Is Actually Easy With One Trick!",
    "url": "https://www.youtube.com/watch?v=pcQ22clXaGA",
    "duration": "7:04",
    "tags": [
      "jee advanced",
      "limit to integral",
      "riemann sum",
      "iit jee math",
      "advanced calculus",
      "math tricks",
      "conceptual limits",
      "definite integration",
      "class 12 math",
      "factorial academy"
    ]
  },
  {
    "title": "Most Conceptual Trigonometric Equation Problem | JEE 2026 & JEE 2027",
    "url": "https://www.youtube.com/watch?v=jZqoLrqQYIg",
    "duration": "10:06",
    "tags": [
      "trigonometry equations",
      "jee advanced math",
      "conceptual math problems",
      "math olympiad",
      "every root is common",
      "jee 2026 preparation",
      "advanced trig identities",
      "jee mains and advanced",
      "math proofs jee"
    ]
  },
  {
    "title": "Students Often Go Wrong Here! Tricky Integration Problem Explained",
    "url": "https://www.youtube.com/watch?v=m4_H0fS2Ed8",
    "duration": "7:56",
    "tags": [
      "integration tricks",
      "definite integration",
      "jee advanced integration",
      "integration substitution",
      "jee mains calculus",
      "f(y) + c",
      "integration differentiation trap",
      "math mistakes",
      "factorial academy"
    ]
  },
  {
    "title": "Powerful Concept from AOD: Equal Roots in Polynomials",
    "url": "https://www.youtube.com/watch?v=7COfoTrcHSQ",
    "duration": "5:41",
    "tags": [
      "jee advanced",
      "application of derivatives",
      "triple root",
      "multiplicity of roots",
      "jee main important questions",
      "calculus concept",
      "iit jee preparation",
      "factorial academy"
    ]
  },
  {
    "title": "3 Limit-Based Integration Problems That Every JEE Aspirant Must Know! | Definite Integration",
    "url": "https://www.youtube.com/watch?v=08VPxjHsXq8",
    "duration": "16:00",
    "tags": [
      "limit integration jee",
      "definite integration tricks",
      "iit jee calculus",
      "jee advanced limits",
      "riemann sum jee",
      "logarithmic limit problems",
      "math olympiad limits",
      "iit jee maths",
      "integration by riemann sum"
    ]
  },
  {
    "title": "A Tough Locus Problem | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=6zlukdEVffg",
    "duration": "9:07",
    "tags": [
      "jee advanced",
      "coordinate geometry",
      "straight line locus",
      "jee straight line tricks",
      "perpendicular distance locus",
      "foot of perpendicular",
      "jee locus questions",
      "factorial academy",
      "jee mains",
      "jee 2025",
      "advanced geometry"
    ]
  },
  {
    "title": "This Beautiful Series Has a Fibonacci Pattern! | JEE | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=bS0M2KdQB7c",
    "duration": "7:13",
    "tags": [
      "fibonacci series",
      "infinite series jee",
      "jee advanced series questions",
      "fibonacci sum",
      "fibonacci over powers of 2",
      "iit jee maths",
      "series tricks jee",
      "infinite series explained",
      "jee advanced maths",
      "factorial academy"
    ]
  },
  {
    "title": "Simple Yet Elegant Integration | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=fdrEkslziFk",
    "duration": "4:17",
    "tags": [
      "jee maths",
      "indefinite integration",
      "simple integration tricks",
      "jee 2025 preparation",
      "jee advanced math",
      "integration using log",
      "maths for iit",
      "factorial academy",
      "class 12 maths"
    ]
  },
  {
    "title": "Can You Crack This Tough Integral ? | Indefinite Integration | Factorial's Question if the Day",
    "url": "https://www.youtube.com/watch?v=Y2vwo-AAgOE",
    "duration": "11:13",
    "tags": [
      "jee advanced integration",
      "indefinite integration",
      "algebraic manipulation",
      "tough jee problems",
      "class 12 maths",
      "integration tricks",
      "jee mains math",
      "iit jee practice",
      "integration by parts",
      "smart math techniques"
    ]
  },
  {
    "title": "Deceptive Inequality? It's Easier Than You Think | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=B9vmJ9S3Zr4",
    "duration": "6:22",
    "tags": [
      "inequality jee advanced",
      "exponential inequality jee",
      "sequence and series jee",
      "clever inequality problems",
      "a^b \\* b^a inequality",
      "am gm inequality",
      "mathematical intuition jee",
      "jee advanced math 2025",
      "inequality tricks",
      "factorial academy"
    ]
  },
  {
    "title": "Sequence Question That Demands Clever Manipulation! | Brilliant Series Question",
    "url": "https://www.youtube.com/watch?v=ovEhmHUsm9U",
    "duration": "7:08",
    "tags": [
      "sequence and series jee",
      "jee advanced sequence",
      "infinite series jee",
      "telescoping series jee",
      "jee advanced tricky question",
      "math manipulation tricks",
      "clever series problems",
      "factorial academy",
      "jee mains 2025 math",
      "iit jee maths advanced"
    ]
  },
  {
    "title": "Smart Yet Simple Approach to JEE 2018 Trig Problem | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=KvjH54h51G0",
    "duration": "4:26",
    "tags": [
      "jee advanced 2018",
      "trigonometric equations",
      "jee trigonometry",
      "simple trigonometry jee",
      "jee with basic methods",
      "no tricks jee",
      "jee maths",
      "class 11 trigonometry",
      "factorial academy"
    ]
  },
  {
    "title": "This is Not What It Looks Like! | Factorial's Question of the Day | JEE",
    "url": "https://www.youtube.com/watch?v=PflqyadoTAA",
    "duration": "9:54",
    "tags": [
      "jee advanced",
      "jee 2025",
      "math tricks",
      "greatest integer function",
      "definite integration",
      "series to integral",
      "beautiful jee questions",
      "mathematics",
      "area under curve",
      "iit jee",
      "factorial academy"
    ]
  },
  {
    "title": "JEE Advanced's Best Graph Question? | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=W-xbP4TlyIc",
    "duration": "16:52",
    "tags": [
      "jee advanced",
      "jee advanced 2019",
      "graph based question",
      "calculus jee",
      "maximum minimum problems",
      "jee maths",
      "sin(πx)/x²",
      "advanced level graph questions",
      "iit jee",
      "local maxima minima",
      "advanced calculus",
      "factorial academy"
    ]
  },
  {
    "title": "Elegant Solution to a Deceptive Cubic! | JEE | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=z9qo8lEb0I0",
    "duration": "5:21",
    "tags": [
      "jee advanced",
      "jee 2026",
      "jee 2027",
      "rational root theorem",
      "polynomial equations",
      "cubic equation",
      "iit jee maths",
      "factorial academy",
      "tricky jee question",
      "rational roots",
      "elegant method jee",
      "jee maths concepts"
    ]
  },
  {
    "title": "2 Powerful Indefinite Integration Problems You Must Master! | JEE 2026",
    "url": "https://www.youtube.com/watch?v=JYN52prmr4w",
    "duration": "6:57",
    "tags": [
      "indefinite integration jee advanced",
      "integration jee mains",
      "jee advanced maths",
      "rational functions integration",
      "trigonometric integrals",
      "integration tricks",
      "calculus jee advanced",
      "integration by substitution",
      "toughest jee maths questions",
      "integration questions for jee",
      "jee 2026 maths",
      "jee 2027 preparation",
      "factorial academy",
      "jee integration"
    ]
  },
  {
    "title": "Why This Series Will Never Cross a Limit! | JEE 2026",
    "url": "https://www.youtube.com/watch?v=cP1xmd6sNsg",
    "duration": "6:47",
    "tags": [
      "jee advanced",
      "sequence and series",
      "number theory jee",
      "jee 2026",
      "jee 2027",
      "odd numbers",
      "jee maths",
      "maths problem solving",
      "factorial academy",
      "harmonic series",
      "challenging jee problems",
      "algebra tricks",
      "ntse",
      "jee concepts"
    ]
  },
  {
    "title": "The Most Beautiful Series Trick – JEE Advanced | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=kZsbzCa3PYg",
    "duration": "6:28",
    "tags": [
      "jee advanced",
      "maths tricks",
      "infinite series",
      "iit jee 2026",
      "jee 2027",
      "algebra",
      "jee series questions",
      "iit jee preparation",
      "sequence and series",
      "factorial academy",
      "maths with tricks",
      "jee playlist",
      "advanced algebra"
    ]
  },
  {
    "title": "Inverse Trigonometry Equation Solved Graphically | cos⁻¹x = 2cot⁻¹(2x + 1) | JEE 2026",
    "url": "https://www.youtube.com/watch?v=gc8iRvzI5io",
    "duration": "7:22",
    "tags": [
      "jee advanced inverse trigonometry",
      "cos inverse cot inverse equation",
      "inverse trigonometric graph",
      "jee maths",
      "advanced math problems",
      "inverse trig jee",
      "tricky math questions",
      "jee advanced 2025 preparation",
      "jee concepts",
      "graphical method jee",
      "graphs in jee maths",
      "cosβ = α type problems",
      "periodic function solutions"
    ]
  },
  {
    "title": "JEE Inequality Problem Solved by Two Elegant Methods | Factorial's Question of the Day | JEE 2026",
    "url": "https://www.youtube.com/watch?v=piswvqJZycY",
    "duration": "13:40",
    "tags": [
      "jee advanced inequality",
      "algebra with parameter",
      "two methods for inequality",
      "quadratic inequality jee",
      "jee algebra trick",
      "jee advanced short method",
      "math problem solving",
      "graphical method",
      "common solution inequality",
      "multiple methods jee"
    ]
  },
  {
    "title": "Hidden Symmetry in This Tough Polynomial Question | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=lYMiMUQBSQU",
    "duration": "9:03",
    "tags": [
      "jee advanced polynomial",
      "algebraic manipulation",
      "degree 6 polynomial",
      "hidden symmetry jee",
      "m plus root n form",
      "polynomial substitution trick",
      "high level algebra jee",
      "jee root form question",
      "factorial academy",
      "jee pattern questions",
      "x + 1/x substitution",
      "advanced factorisation tricks"
    ]
  },
  {
    "title": "Beautiful JEE 2008 Geometry Problem - But There's a Mistake! | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=Kg4AGtgjGtQ",
    "duration": "14:37",
    "tags": [
      "jee advanced 2008",
      "jee advanced geometry",
      "ps st qr inequality",
      "jee circle question",
      "sequence and series in geometry",
      "am gm inequality jee",
      "conceptual geometry jee",
      "jee advanced hidden mistake",
      "unexpected math connections",
      "advanced geometry question",
      "factorial academy"
    ]
  },
  {
    "title": "Conceptual Inequality Based on Concavity | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=7hoKLIO3dSc",
    "duration": "9:03",
    "tags": [
      "jee advanced maths",
      "jensen inequality jee",
      "concavity concept",
      "comparing surds",
      "inequality tricks jee",
      "math olympiad techniques",
      "conceptual math questions",
      "surd comparison without calculator",
      "advanced math reasoning",
      "jensen inequality surds",
      "factorial academy"
    ]
  },
  {
    "title": "Can You Find Range of This Function? | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=0F7oUmP7nz8",
    "duration": "6:34",
    "tags": [
      "jee advanced maths",
      "range of product functions",
      "cos x sin x root functions",
      "trigonometry jee",
      "class 12 maths",
      "advanced function range",
      "product of trig functions",
      "iit jee maths tricks",
      "cauchy schwarz inequality",
      "inequality in trigonometry",
      "range using inequality"
    ]
  },
  {
    "title": "JEE Advanced 2023 Sequence & Series Puzzle | Hidden Pattern + Smart Approach",
    "url": "https://www.youtube.com/watch?v=QAG70XsmzGs",
    "duration": "9:14",
    "tags": [
      "jee advanced 2023",
      "sequence and series jee",
      "jee number theory",
      "jee math puzzle",
      "advanced level math",
      "jee pattern problems",
      "math tricks jee",
      "jee 2026",
      "jee 2025",
      "qotd jee",
      "factorial academy"
    ]
  },
  {
    "title": "Tricky Polynomial with Real Roots Condition | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=1de4Ik7SJr8",
    "duration": "7:07",
    "tags": [
      "jee advanced polynomial",
      "polynomial real roots condition",
      "jee 2025 polynomial",
      "jee advanced tricky questions",
      "range of parameter k",
      "jee maths advanced",
      "jee polynomials",
      "quadratic manipulation jee",
      "real roots jee advanced",
      "polynomial with real roots",
      "factorial academy",
      "jee main advanced preparation"
    ]
  },
  {
    "title": "Quadratic Equation + Number Theory = Conceptual Gold! | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=8qeZroBj_gg",
    "duration": "7:21",
    "tags": [
      "jee advanced number theory",
      "jee advanced quadratic",
      "rational roots jee",
      "number theory jee tricks",
      "jee conceptual math",
      "quadratic equation rational roots",
      "factorial academy",
      "jee 2025",
      "jee mains 2025",
      "iit jee number theory"
    ]
  },
  {
    "title": "Conceptual Trap in Question | JEE Aspirants Beware! | Quadratic Equation | JEE 2026",
    "url": "https://www.youtube.com/watch?v=TZAvXyVyBqk",
    "duration": "8:26",
    "tags": [
      "jee advanced 2025",
      "jee advanced quadratic",
      "quadratic equations tricks",
      "conceptual math question",
      "jee conceptual question",
      "nature of roots",
      "iit jee preparation",
      "quadratic equations jee",
      "factorial academy",
      "advanced level math",
      "math traps jee"
    ]
  },
  {
    "title": "Quadratic Equation Question with a Clever Twist | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=AFAu-0Y5mWw",
    "duration": "6:51",
    "tags": [
      "quadratic equations",
      "jee advanced 2025",
      "power of roots",
      "algebraic manipulation",
      "quadratic tricks",
      "jee maths",
      "alpha beta roots",
      "factorial academy",
      "quadratic identity",
      "iit jee shortcuts",
      "advanced algebra",
      "factorial question of the day"
    ]
  },
  {
    "title": "Mastering AM-GM & Titu's Lemma | 1 Solved + 2 Homework | JEE 2026",
    "url": "https://www.youtube.com/watch?v=2TFbf2b3q7M",
    "duration": "4:18",
    "tags": [
      "am gm inequality",
      "titu's lemma",
      "inequality tricks",
      "jee maths",
      "jee advanced inequality",
      "am gm proof",
      "titu lemma application",
      "factorial academy",
      "inequality homework",
      "jee advanced 2025"
    ]
  },
  {
    "title": "Modulus Question Solved Elegantly | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=X8Z8O3rV9fg",
    "duration": "8:31",
    "tags": [
      "jee advanced 2025",
      "modulus function",
      "modulus trick jee",
      "modulus equations",
      "jee maths modulus",
      "elegant solution jee",
      "factorial academy",
      "jee maths 2025",
      "iit jee modulus",
      "smart math tricks"
    ]
  },
  {
    "title": "Special Approach to Solve a Tough Quartic | Quadratic Equations | JEE 2026",
    "url": "https://www.youtube.com/watch?v=3OuBWhSofeI",
    "duration": "8:40",
    "tags": [
      "jee advanced 2025",
      "quadratic equations jee",
      "quartic equation jee",
      "4th degree equation trick",
      "jee math special question",
      "factorial academy",
      "polynomial equation jee",
      "jee problem solving",
      "iit jee 2025 math",
      "advanced maths for jee"
    ]
  },
  {
    "title": "Beautiful Telescoping Series Question | Sequence & Series | JEE 2026",
    "url": "https://www.youtube.com/watch?v=JFUv4lZ-Klc",
    "duration": "10:08",
    "tags": [
      "jee advanced 2025",
      "sequence and series jee",
      "telescopic series",
      "jee telescoping series",
      "jee maths advanced level",
      "factorial academy",
      "advanced maths practice",
      "jee series questions",
      "telescoping sum jee",
      "series manipulation tricks",
      "iit jee maths"
    ]
  },
  {
    "title": "Paragraph Involving Recursion Series | A Brilliant Question | Limits | JEE 2026",
    "url": "https://www.youtube.com/watch?v=FOpIjn33Jzk",
    "duration": "8:06",
    "tags": [
      "jee advanced 2025",
      "jee advanced paragraph questions",
      "limits jee advanced",
      "recursion series jee",
      "paragraph type jee questions",
      "jee maths limits",
      "iit jee 2025",
      "factorial academy",
      "advanced level maths",
      "jee paragraph based questions",
      "recursion in limits",
      "sequence and series jee"
    ]
  },
  {
    "title": "When Determinants Meet Differentiation – A Smart JEE Advanced Question | JEE 2026",
    "url": "https://www.youtube.com/watch?v=FPLjJSNpdFw",
    "duration": "8:16",
    "tags": [
      "jee advanced 2025",
      "jee advanced questions",
      "determinants jee",
      "differentiation jee",
      "mixed concept jee",
      "jee advanced important questions",
      "factorial academy",
      "algebra and calculus",
      "inter-topic jee questions",
      "derivative of determinant",
      "conceptual jee question",
      "jee advanced shortcuts",
      "iit jee 2025 preparation"
    ]
  },
  {
    "title": "Quadratics Done Right: Common Root + Conceptual Twist | JEE 2026",
    "url": "https://www.youtube.com/watch?v=zt1aHgGqv9k",
    "duration": "9:13",
    "tags": [
      "quadratic equations jee",
      "common root jee question",
      "jee advanced quadratic",
      "jee maths tricks",
      "relation between roots and coefficients",
      "jee 2025 maths",
      "conceptual quadratic question",
      "jee algebra",
      "factorial academy",
      "jee mains 2022"
    ]
  },
  {
    "title": "Smart Manipulation in Differentiation | Factorial's Question of the Day | JEE 2026",
    "url": "https://www.youtube.com/watch?v=5LRtWOQ9iFE",
    "duration": "5:02",
    "tags": [
      "differentiation jee advanced",
      "polynomial differentiation jee",
      "jee maths tricks",
      "calculus jee advanced",
      "jee 2025 maths",
      "derivative manipulation",
      "jee calculus concepts",
      "differentiation shortcut",
      "factorial academy",
      "iit jee maths"
    ]
  },
  {
    "title": "Trigonometric Equation with 3 Interesting Parts! | Factorial's Question if the Day",
    "url": "https://www.youtube.com/watch?v=TKB0gpJJm5k",
    "duration": "8:03",
    "tags": [
      "trigonometric equations",
      "jee advanced trigonometry",
      "jee 2025 trigonometry",
      "multi-part trigonometry question",
      "factorial academy",
      "jee advanced questions",
      "jee maths trigonometry",
      "jee preparation 2025",
      "trigonometry jee solved",
      "jee mains and advanced",
      "jee maths practice",
      "jee 2026 maths"
    ]
  },
  {
    "title": "Easy Question from Differentiation | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=_kwHDQZBU3w",
    "duration": "4:21",
    "tags": [
      "jee advanced differentiation",
      "product rule jee",
      "jee maths question",
      "differentiation jee tricks",
      "factorial academy",
      "calculus jee advanced",
      "jee 2025 maths",
      "product of functions jee"
    ]
  },
  {
    "title": "Simple Manipulation, Smart Solution | Trigonometry | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=uu2S5PfhL88",
    "duration": "3:32",
    "tags": [
      "jee advanced trigonometry",
      "smart trigonometry tricks",
      "jee 2025 maths",
      "trigonometric identity jee",
      "factorial academy",
      "jee advanced short tricks",
      "jee maths problem solving"
    ]
  },
  {
    "title": "Beautiful Blend: Trigo + Series + Limits! | Trigonometry | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=aaRXaZUhDVc",
    "duration": "5:55",
    "tags": [
      "jee advanced trigonometry",
      "jee sequence and series",
      "limits jee advanced",
      "mixed concept jee questions",
      "factorial academy",
      "advanced level math",
      "jee 2025 preparation"
    ]
  },
  {
    "title": "Perfect Telescoping Series Question! | Sequence & Series | Factorial's Question of the Day | JEE2026",
    "url": "https://www.youtube.com/watch?v=4cRXal2ZlFc",
    "duration": "7:04",
    "tags": [
      "telescoping series jee",
      "sequence and series jee",
      "jee advanced math",
      "infinite series jee",
      "jee math tricks",
      "factorial academy",
      "jee advanced preparation",
      "telescopic sum jee",
      "factorial questions",
      "jee2026"
    ]
  },
  {
    "title": "A Telescoping Series? Not Exactly! | Sequence & Series Question | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=kdsUYcmodz4",
    "duration": "6:43",
    "tags": [
      "sequence and series jee",
      "telescoping series jee",
      "sum of series jee",
      "jee advanced series question",
      "factorial academy",
      "jee 2026 math",
      "jee advanced preparation",
      "jee series tricks"
    ]
  },
  {
    "title": "Test Your Concepts: Differentiation Edition | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=vQmkJ44ROeo",
    "duration": "4:16",
    "tags": [
      "differentiation jee",
      "conceptual differentiation jee",
      "jee advanced calculus",
      "math jee 2026",
      "jee advanced problems",
      "jee differentiation",
      "factorial academy",
      "derivative jee questions"
    ]
  },
  {
    "title": "A Conceptual Question | Differentiability | Factorial's Question of the Day #10 | JEE 2026",
    "url": "https://www.youtube.com/watch?v=_I0wbkqs4rw",
    "duration": "4:54",
    "tags": [
      "differentiability jee",
      "jee advanced differentiability",
      "calculus jee problems",
      "math jee advanced",
      "left and right derivative",
      "jee traps calculus",
      "factorial academy",
      "differentiability concepts jee"
    ]
  },
  {
    "title": "Infinite Series Simplified! | Sequence & Series | JEE 2026 | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=4MR4AHhxwR0",
    "duration": "6:42",
    "tags": [
      "infinite series jee",
      "sum of series jee",
      "jee advanced sequence and series",
      "smart manipulation series",
      "jee infinite series tricks",
      "factorial academy",
      "jee advanced 2026 math",
      "sequence series concepts"
    ]
  },
  {
    "title": "Beautiful Differentiability Question | JEE 2000 PYQ | Factorial's Question of the Day #8",
    "url": "https://www.youtube.com/watch?v=1T84yUM_Jt0",
    "duration": "4:52",
    "tags": [
      "differentiability jee",
      "differentiability question jee advanced",
      "jee pyq differentiability",
      "jee 2000 math question",
      "calculus jee",
      "jee advanced 2026",
      "factorial academy",
      "piecewise function jee",
      "continuity and differentiability"
    ]
  },
  {
    "title": "Continuous Product in Limits? | Beautiful JEE Concept | Factorial's Question of the Day #7",
    "url": "https://www.youtube.com/watch?v=NYzWXEmD2OQ",
    "duration": "7:36",
    "tags": [
      "limit of product",
      "product series jee",
      "infinite product jee advanced",
      "jee advanced limits",
      "factorial academy",
      "jee 2026 preparation",
      "continuous product calculus",
      "calculus jee advanced",
      "limits tricky question",
      "qotd jee"
    ]
  },
  {
    "title": "A Beautiful Concept in Limits | Rational vs Irrational | Factorial's Question of the Day #6",
    "url": "https://www.youtube.com/watch?v=B8XI7ZWPovc",
    "duration": "5:44",
    "tags": [
      "limits jee advanced",
      "rational irrational limits",
      "jee advanced qotd",
      "factorial academy",
      "jee 2026 preparation",
      "limits conceptual question",
      "piecewise limit",
      "rational vs irrational x",
      "math limit trick",
      "calculus jee"
    ]
  },
  {
    "title": "Recursion Series in Limits | Smart Substitution Trick | Factorial's Question of the Day #5",
    "url": "https://www.youtube.com/watch?v=-AXfewA5cUg",
    "duration": "6:47",
    "tags": [
      "jee advanced limits",
      "recursion jee",
      "recursion in limits",
      "smart substitution jee",
      "jee advanced maths",
      "factorial academy",
      "qotd jee",
      "limits jee advanced",
      "jee 2026 practice",
      "recursive sequence jee",
      "question of the day"
    ]
  },
  {
    "title": "It's Not Hard... But It's a Puzzle! | Functional Equation | Factorial's Question of the Day #4",
    "url": "https://www.youtube.com/watch?v=oTj35qWflT0",
    "duration": "3:53",
    "tags": [
      "functional equations jee",
      "jee 2026",
      "jee advanced 2026",
      "functional equation puzzle",
      "jee maths tricky question",
      "jee daily practice",
      "factorial academy",
      "qotd jee",
      "jee functional equation"
    ]
  },
  {
    "title": "Can You Handle This Polynomial Limit? | JEE 2026 | Factorial's Question of the Day #3",
    "url": "https://www.youtube.com/watch?v=GDqf8PPJtng",
    "duration": "6:23",
    "tags": [
      "factorials question of the day",
      "jee 2026",
      "jee advanced 2026",
      "limits jee advanced",
      "polynomial limits jee",
      "jee maths tricky limit",
      "jee calculus practice",
      "factorial academy",
      "qotd jee 2026"
    ]
  },
  {
    "title": "Can You Solve This Functional Equation? | Function |Factorial's Question of the Day #2",
    "url": "https://www.youtube.com/watch?v=QEVAZrDEi-4",
    "duration": "6:04",
    "tags": [
      "factorials question of the day",
      "jee 2026",
      "jee advanced 2026",
      "functional equation jee",
      "periodic functions jee",
      "even function jee",
      "jee maths practice",
      "jee advanced functions",
      "factorial academy",
      "jee challenge series"
    ]
  },
  {
    "title": "Can You Solve This Polynomial Equation | Function | Factorial's Question of the Day",
    "url": "https://www.youtube.com/watch?v=Bqk_nbY_fkM",
    "duration": "6:30",
    "tags": [
      "factorial's question of the day",
      "jee 2026",
      "jee advanced 2026",
      "polynomial jee advanced",
      "jee maths daily",
      "jee 2026 preparation",
      "factorial academy",
      "daily jee challenge",
      "jee advanced question series",
      "math jee 2026"
    ]
  }
];